-- https://www.hackerrank.com/challenges/contest-leaderboard/problem?isFullScreen=true
SELECT H.HACKER_ID, H.NAME, COALESCE(SUM(S.SCORE), 0) MAX_SCORE
FROM HACKERS H
JOIN 
(
    SELECT HACKER_ID, CHALLENGE_ID, COALESCE(MAX(SCORE), 0) SCORE
    FROM SUBMISSIONS
    GROUP BY HACKER_ID, CHALLENGE_ID
) S
ON H.HACKER_ID = S.HACKER_ID
GROUP BY H.HACKER_ID, H.NAME
HAVING MAX_SCORE != 0
ORDER BY MAX_SCORE DESC, H.HACKER_ID
;
