-- https://www.hackerrank.com/challenges/the-company/problem?isFullScreen=true
SELECT E.COMPANY_CODE, C.FOUNDER,
    COUNT(DISTINCT LEAD_MANAGER_CODE),
    COUNT(DISTINCT SENIOR_MANAGER_CODE),
    COUNT(DISTINCT MANAGER_CODE),
    COUNT(DISTINCT EMPLOYEE_CODE)
FROM EMPLOYEE E, COMPANY C
WHERE E.COMPANY_CODE = C.COMPANY_CODE
GROUP BY E.COMPANY_CODE, C.FOUNDER
ORDER BY E.COMPANY_CODE ASC;
