-- https://www.hackerrank.com/challenges/interviews/problem?isFullScreen=true
SELECT A.CONTEST_ID, A.HACKER_ID, A.NAME, A.TS, A.TAS, B.TV, B.TUV
FROM (
    SELECT 
        CONTESTS.`CONTEST_ID` AS 'CONTEST_ID', 
        CONTESTS.`HACKER_ID` AS 'HACKER_ID', 
        NAME,
        COALESCE(SUM(`TOTAL_SUBMISSIONS`), 0) AS 'TS',
        COALESCE(SUM(`TOTAL_ACCEPTED_SUBMISSIONS`),0) AS 'TAS'
    FROM 
        CONTESTS
        LEFT JOIN COLLEGES
            ON COLLEGES.`CONTEST_ID` = CONTESTS.`CONTEST_ID`
        LEFT JOIN CHALLENGES
            ON CHALLENGES.`COLLEGE_ID` = COLLEGES.`COLLEGE_ID`
        LEFT JOIN SUBMISSION_STATS
            ON SUBMISSION_STATS.`CHALLENGE_ID` = CHALLENGES.`CHALLENGE_ID`
    GROUP BY 
        CONTESTS.`CONTEST_ID`, 
        CONTESTS.`HACKER_ID`, 
        NAME
    ORDER BY CONTESTS.`CONTEST_ID`
    ) A
LEFT JOIN 
    (
    SELECT 
        CONTESTS.`CONTEST_ID` AS 'CONTEST_ID', 
        CONTESTS.`HACKER_ID` AS 'HACKER_ID', 
        NAME,
        COALESCE(SUM(`TOTAL_VIEWS`), 0) AS 'TV',
        COALESCE(SUM(`TOTAL_UNIQUE_VIEWS`),0) AS 'TUV'
    FROM 
        CONTESTS
        LEFT JOIN COLLEGES
            ON COLLEGES.`CONTEST_ID` = CONTESTS.`CONTEST_ID`
        LEFT JOIN CHALLENGES
            ON CHALLENGES.`COLLEGE_ID` = COLLEGES.`COLLEGE_ID`
        LEFT JOIN VIEW_STATS
            ON VIEW_STATS.`CHALLENGE_ID` = CHALLENGES.`CHALLENGE_ID`
    GROUP BY 
        CONTESTS.`CONTEST_ID`, 
        CONTESTS.`HACKER_ID`, 
        NAME
    ORDER BY CONTESTS.`CONTEST_ID`
    ) B 
ON A.CONTEST_ID = B.CONTEST_ID AND A.HACKER_ID = B.HACKER_ID
WHERE 
    A.TS != 0 OR A.TAS != 0 OR B.TV != 0 OR B.TUV != 0;
